Revamp vm scripts for building images.

diff --git a/contrib/vm/install-sagecell b/contrib/vm/install-sagecell
--- a/contrib/vm/install-sagecell
+++ b/contrib/vm/install-sagecell
@@ -1,9 +1,10 @@
-#!/bin/bash
+#!/usr/bin/env bash
+set -o errexit
+set -o nounset
+set -o xtrace
 
-set -v
 # These variable names are important for the functions below
 VM=$1
-SAGE_SOURCE=$2
 VMSSH=root@localhost
 VMPORT=2555
 
@@ -13,20 +14,21 @@ source ./vm/install-sagecell-functions
 
 remove_install_log
 update_system
+install_extra_system_packages
 kill_monitor
 remove_accounts
 set_up_sageserver_account
 set_up_sageworker_account
 make_tmp_dir
-upload_sage_source
+upload_repositories
 install_sage
-RC=`grep "Error building Sage" install.log` 
-if [ "$RC" != "" ]; then
-   echo "Error building Sage!"
-   exit 1
+if grep -q "Error building Sage" install.log; then
+    echo "Error building Sage!"
+    exit 1
 fi
 install_sagecell
 install_extra_python_packages
+install_basemap
 copy_sagecell_system_files
 lock_down_sageworker
 set_up_sagecell_firewall
diff --git a/contrib/vm/start-vm b/contrib/vm/start-vm
--- a/contrib/vm/start-vm
+++ b/contrib/vm/start-vm
@@ -1,27 +1,22 @@
-#!/bin/sh
+#!/bin/bash
+set -o errexit
+set -o nounset
+#set -o xtrace
 
-#set -v
 VM=$1
 SSHPORT=$2
 
-STATUS=`virsh dominfo $VM | grep 'State:.*running'`
-if [ $? -ne 0 ]; then
-    virsh start $VM
-    if [ $? -ne 0 ]; then
-       echo "Failed to start virtual machine!"
+if [[ `virsh domstate $VM` != "running" ]]; then
+    if ! virsh start $VM; then
+       echo "Failed to start $VM!"
        exit 1
     fi
-    STATUS="booting"
     echo "Booting $VM"
-    sleep 2
+    sleep 5
 fi
 
-sleep 3
-
 ./vm/forward-port $VM $SSHPORT 22
-STATUS=`ssh -oNoHostAuthenticationForLocalhost=yes root@localhost -p $SSHPORT echo "ready"`
-while [ "$STATUS" != "ready" ]; do
-    echo "Waiting for VM to start."
+while [[ `ssh -oNoHostAuthenticationForLocalhost=yes root@localhost -p $SSHPORT echo "ready"` != "ready" ]]; do
+    echo "Waiting for $VM to start."
     sleep 5
-    STATUS=`ssh -oNoHostAuthenticationForLocalhost=yes root@localhost -p $SSHPORT echo "ready"`
 done
